### ISSUE TITLE
ImportError: No module named neopixel

### ISSUE THREAD

**Issue by gerbattiston** [ThatFLFeeling/MagicBandReader#2]
Hi there! I have everything set up on my raspberry pi, I was able to follow the steps to test the led strip and everything works fine.
But when I try to run `magicBandReader.py` I get an error, how are you running it?
Thanks!

I also tried using this repo and the test worked fine: https://github.com/jgarff/rpi_ws281x

**Comment by ThatFLFeeling** [comment]
Hi! Is the error you’re getting the import error on the neopixel library?
Try importing that library and running again. If you’re getting a different
error, what are the details?
Thanks!

**Comment by gerbattiston** [comment]
So I cloned your code and executed:
`sudo python3 magicBandReader.py` and it throws that import error

**Comment by gerbattiston** [comment]
I GOT IT!!!
